# vim: set ft=toml:
[ids]
*

[main]

capslock = overload(special, noop)

# rightshift as the tmux prefix
rightshift = macro2(0, 0, C-b)

# Do nothing then super key is pressed. This avoids opening default desktop
# environment finders
leftmeta = overload(meta, noop)

rightcontrol = layer(auxiliary)
compose = layer(auxiliary)

[alt]
tab = noop

[special]
# backtick dead key
leftbrace = macro(leftshift+leftbrace leftshift+leftbrace)

# tilde dead key
' = macro(' ')

# double quotes on [
] = ~

# single quotes on ]
\ = `

h = left
j = down
k = up
l = right
p = sysrq
0 = home
4 = end
u = pageup
d = pagedown

i = insert
backspace = delete
enter = esc
semicolon = M-w
compose = compose
rightcontrol = layer(control)

[auxiliary]
1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
0 = f10
minus = f11
equal = f12
capslock = capslock

e = M-w
x = A-f4
tab = A-tab

# moving windows around
s = M-down
w = M-up
a = M-left
d = M-right
