[ids]

*

[main]

# rightshift as the tmux prefix
rightshift = C-b

capslock = overload(special, noop)

# Do nothing then super key is pressed. This avoids opening default desktop
# environment finders
leftmeta = overload(meta, noop)

[shift]

# Sends capslock when pressing both shift keys
leftshift = capslock
rightshift = capslock

[special]

# backtick dead key
leftbrace = macro(leftshift+leftbrace leftshift+leftbrace)

# tilde dead key
' = macro(' ')

# double quotes on [
] = ~

# single quotes on ]
\ = `

h = left
j = down
k = up
l = right
p = sysrq

0 = home
4 = end
u = pageup
d = pagedown
i = insert
backspace = delete

enter = esc
