# vim: set ft=toml:
[ids]
*

[main]

capslock = overload(special, noop)

# rightshift as the tmux prefix
rightshift = C-b

# Do nothing then super key is pressed. This avoids opening default desktop
# environment finders
leftmeta = overload(meta, noop)

[alt]
tab = noop

[special]
a = oneshot(auxiliary)
q = oneshot(tmux)

# backtick dead key
leftbrace = macro(leftshift+leftbrace leftshift+leftbrace)

# tilde dead key
' = macro(' ')

# double quotes on [
] = ~

# single quotes on ]
\ = `

h = left
j = down
k = up
l = right
p = sysrq
0 = home
4 = end
u = pageup
d = pagedown

i = insert
backspace = delete

enter = esc
semicolon = M-w

[auxiliary]
1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
0 = f10
minus = f11
equal = f12
capslock = capslock

# ; -> :
/ = ?
meta = M-w
backspace = A-f4
p = A-tab

# moving windows around
j = M-down
k = M-up
h = M-left
l = M-right
leftshift = layer(auxiliary_shift)

[auxiliary_shift]
h = S-M-left
l = S-M-right

[tmux]
j = macro(C-b s)
h = macro(C-b p)
l = macro(C-b n)
p = macro(C-b q)
equal = macro(C-b E)
alt = layer(tmux_meta)

0 = macro(C-b 0)
1 = macro(C-b 1)
2 = macro(C-b 2)
3 = macro(C-b 3)
4 = macro(C-b 4)
5 = macro(C-b 5)
6 = macro(C-b 6)
7 = macro(C-b 7)
8 = macro(C-b 8)
9 = macro(C-b 9)

[tmux_meta]
j = macro(C-b A-down)
k = macro(C-b A-up)
h = macro(C-b A-left)
l = macro(C-b A-right)
